# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - wineapp2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://wineapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1025c97d3d664e408039ddddc16202d1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_05808eb57e4a4285b36b1dac5e6fcd79 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: wineapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1025c97d3d664e408039ddddc16202d1 }}/wine:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wineapp2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0b86fb1f793740b3842c8d20eab29d19 }}
        images: 'wineapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1025c97d3d664e408039ddddc16202d1 }}/wine:${{ github.sha }}'